/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CoflCore;

import CoflCore.misc.SessionManager;
import org.greenrobot.eventbus.EventBus;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Path;

public class CoflCore {
    public static void setSocket(Socket socket) {
        CoflCore.socket = socket;
    }

    private static Socket socket;


    public void setupSocket(String username, Path pathToConfig) throws IOException, URISyntaxException {
        SessionManager.setMainPath(pathToConfig);
        String uri = "wss://sky.coflnet.com/modsocket?player=" + username + "&version=1.5.2-Alpha";
        SessionManager.UpdateCoflSessions();
        String coflSessionID = SessionManager.GetCoflSession(username).SessionUUID;
        uri += "&SId=" + coflSessionID;
        socket = new Socket(new URI(uri));
    }

    public void registerEventFile(Object target) {
        EventBus.getDefault().register(target);
    }

    public void unregisterEventFile(Object target) {
        EventBus.getDefault().unregister(target);
    }

    public void sendCommand(String command) {
        if(socket == null) throw new NullPointerException("Socket is not setup");
        socket.send(command);
    }
}
