/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CoflCore;

import CoflCore.events.ReceiveCommand;
import CoflCore.events.SocketOpen;
import org.greenrobot.eventbus.Subscribe;
import org.junit.Test;

import java.io.IOException;
import java.net.URISyntaxException;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() throws IOException, URISyntaxException {
//        Library classUnderTest = new Library();
//        classUnderTest.setupSocket("Conutik", null);
//        classUnderTest.registerEventFile(this);
//        new Thread(() -> {
//            try {
//                Thread.sleep(5000);
//            } catch (InterruptedException e) {
//                throw new RuntimeException(e);
//            }
//            classUnderTest.sendCommand("{\"type\":\"chat\",\"data\":\"\"test\"\"}");
//            Thread.currentThread().interrupt();
//        }).start();
    }

//    @Subscribe
//    public void onOpen(SocketOpen e) {
//        System.out.println("Socket opened");
//    }
//
//    @Subscribe
//    public void onMessage(ReceiveCommand e) {
//        System.out.println(e.command.getType().toString());
//    }
}
